version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=go-todo
      - DATABASE_SSLMODE=disable
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - go-todo-network

  postgres:
    image: postgres:latest
    container_name: go-todo-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=go-todo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - go-todo-network

volumes:
  postgres-data:

networks:
  go-todo-network:
    driver: bridge