server:
  port: 8080
  readTimeout: 10
  writeTimeout: 10

database:
  host: localhost
  port: 5432
  user: postgres
  password: 1234
  name: go-todo
  sslmode: disable
  timezone: UTC
  superAdmin: super_admin@todo.com
  superAdminPassword: todo@1234

jwt:
  secret: 05cd349d9acfba3662a8bbc07bba0dbfdbc513d569e9475c97a029779a0bb41b
  expiresIn: 3600

logging:
  level: info
  file: ./logs/todo.log
